language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - openjdk8

scala:
  - 2.12.8

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt